### ISSUE TITLE
Which branch should we be on to follow the code along?

### ISSUE THREAD

**Issue by clydegrey** [mike-works/pwa-fundamentals#139]
Master doesn't have a server/cli directory, so it must be a different branch but am having trouble identifying which one. Thanks in advance.

**Comment by mike-north** [comment]
If you want to start up the backend, the main script is `./server/index`. Please let me know if [these instructions in the README on master](https://github.com/mike-works/pwa-fundamentals#project-setup) do not work out for you.

Good luck, have fun!
